### ISSUE TITLE
gandi account crash

### ISSUE THREAD

**Issue by skitoo** [Gandi/gandi.cli#169] opened 2015-12-25 12:38 UTC
Hi,

When I use the command ```gandi account``` I have the following crash

```
Traceback (most recent call last):
  File "/usr/bin/gandi", line 9, in <module>
    load_entry_point('gandi.cli==0.16', 'console_scripts', 'gandi')()
  File "/usr/lib/python2.7/site-packages/gandi/cli/__main__.py", line 8, in main
    cli(obj={})
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/gandi/cli/core/cli.py", line 168, in invoke
    click.Group.invoke(self, ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/gandi/cli/commands/account.py", line 15, in info
    account = gandi.account.all()
  File "/usr/lib/python2.7/site-packages/gandi/cli/modules/account.py", line 38, in all
    left = account['credits'] / creditusage
ZeroDivisionError: integer division or modulo by zero
```

**Comment by ziir** [comment] 2015-12-25 13:09
Hello @skitoo, thanks for the report :)

This bug is known. Duplicate of #151 
Quoting @sayoun from https://github.com/Gandi/gandi.cli/issues/151#issuecomment-145440835

```
It's fixed in commit 2a596d4
It will be included in next release 0.17 but you can use the latest master from github until then.
```

**Closed by ziir** 2015-12-25 13:09 UTC
Labels: bug, duplicate
