### ISSUE TITLE
No configuration found, please use 'gandi setup' command

### ISSUE THREAD

**Issue by jmaeder** [Gandi/gandi.cli#40] opened 2014-10-08 16:41 UTC
Hi,

I installed gandi.cli with pip and virtualenv on Mac OS X Yosemite (Beta 4). Then, i run through setup configuring, ote and production API Key.

Unfortunately, i got a "No configuration found" when i try to execute a cli command (i.e. gandi vm create)

Could you please help?
Thanks
Jérôme.

**Comment by ziir** [comment] 2015-09-16 21:34
I couldn't reproduce the issue on my macbook running Yosemite.
Surely we can close this issue now ?

**Closed** 2015-09-17 09:42 UTC
Labels: question
